### ISSUE TITLE
use official images, or an official IBM docker repo.

### ISSUE THREAD

**Issue by paulczar** [IBM/kubernetes-container-service-gameon-java-microservice#14]
Some of the images in this repo are unofficial, and sometimes not even automated builds so you can't click back to see the authenticity/makeup of the image.   We should ensure that all images are either the official ones from docker ( or the software maker ) or part of an IBM docker repo with automated build etc turned on.

We should also pin them where possible to specific versions to help reduce the chance of upstream changes breaking the demo.

Here are some examples gathered from the k8s manifest files in the repo ...  this is not all, just a few from a  quick dig through:

## [keystore](https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes/blob/master/setup.yaml#L12)

This one is unpinned and is from a personal repo with no automated build or other information to show where it came from and if its authentic.  It would be better if it came from an IBM docker repo and was pinned.

## [kafka](https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes/blob/master/platform/kafka.yaml#L32)

This one is also unpinned and from a personal repo, its a year old and is not automated build and has no details on where to find the origin dockerfile etc.

There does not appear to be an official image, however there are several that appear to have a good well known author/source:

* https://hub.docker.com/r/wurstmeister/kafka/
* https://hub.docker.com/r/tianon/kafka/
* https://hub.docker.com/r/spotify/kafka/

## [couchdb](https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes/blob/master/platform/couchdb.yaml#L32)

This one is pinned and has autobuild on, but if possible would be better to use the official repo

https://hub.docker.com/r/klaemo/couchdb/

**Comment by AnthonyAmanse** [comment]
Created pull request #15 

1. keystore - was using the Dockerfile in `containers/setup/`. Added reference in main README in pr
2. couchdb - is now using image from [official repo](https://hub.docker.com/_/couchdb/)

Will be testing another kafka image

**Comment by animeshsingh** [comment]
Done
