### ISSUE TITLE
Test usage of hostPath PersistentVolume

### ISSUE THREAD

**Issue by shivahr** [IBM/kubernetes-container-service-gameon-java-microservice#26]
Bluemix Container service got its Kubernetes server version upgraded to v1.7.4 recently. After this upgrade, we started seeing issues with hostPath PersistentVolumes (PV) as reported in https://github.com/IBM/deploy-graph-db-container/issues/3 (we had no such issues with the older v.1.5.x Kubernetes server version). Since this repo also uses hostPath PV, please test it out once and see if you need similar fix.

**Comment by AnthonyAmanse** [comment]
hostPath works with new clusters. Tested on 1.7 and 1.8
