### ISSUE TITLE
Explore Minikube for this

### ISSUE THREAD

**Issue by animeshsingh** [IBM/kubernetes-container-service-gameon-java-microservice#6]
As per Tim Robinson - some issues

looking at the GameOn journey WIP… worked well using Deploy Toolchain button. But not so good with minikube on my Mac on 0.18.0 (latest). The problem I saw was that kubectl get nodes came back with a name instead of public IP of the cluster. All went good until trying to start the core services. Lots of

[ALERT] 124/015539 (10) : parsing [/etc/haproxy/haproxy-dev.cfg:97] : 'server room1' : invalid address: 'minikube' in 'minikube:30980'

[ALERT] 124/015539 (10) : parsing [/etc/haproxy/haproxy-dev.cfg:110] : 'server map1' : invalid address: 'minikube' in 'minikube:30947'

messages popping up. So I deleted it all and changed the replace IP script with the docker-machine ip of 192.168.99.100 and re-ran. Then it was happier. Things seem to start. However, the application seems to have problems working correctly. Not getting good information when moving to a room, unable to move back to the starting room. Were you getting better results with minikube?

some minor easy fixes I’d suggest. add an s (silent) option to these commands to just return the response codes:

curl -w "%{http_code}" "<Public IP of your cluster>:31200/health" -o /dev/null

should be

curl -sw "%{http_code}" "<Public IP of your cluster>:31200/health" -o /dev/null

I’d suggest to move to the teardown instructions the kubectl delete pod setup command. That way folks that use deploy to toolchain button will see it when doing the other cleanup.

final thing… drop the “s” from Dockers in the Reference item.

**Comment by ebullient** [comment]
Ozzy and I will likely have a crack at this as we port the core game itself over..

**Comment by AnthonyAmanse** [comment]
It should now be working on minikube #21. Changed an environment variable on the Kafka deployment from `kafka` to `localhost`. IP address to be used is in `minikube ip`. Tested on latest minikube release (v0.21.0)
